//defines.h
#define SETBIT(WORD,BIT) WORD|=1<<BIT
#define CLRBIT(WORD,BIT) WORD&=~(1<<BIT)
#define CPLBIT(WORD,BIT) WORD^=1<<BIT
#define READBIT(WORD,BIT) ((WORD>>BIT)&1)
#define WRITEBIT(WORD,BITPOS,BIT)   WORD=((WORD&~(1<<BITPOS))|(BIT<<BITPOS))

#define WRITENIBBLE(WORD,BITSTARTPOS,VAL)  WORD=((WORD&~(15<<BITSTARTPOS))|(VAL<<BITSTARTPOS))
							
#define READNIBBLE(WORD,BITSTARTPOS) ((WORD>>BITSTARTPOS)&15)
				
#define WRITEBYTE(WORD,BITSTARTPOS,VAL) WORD=((WORD&~(255<<BITSTARTPOS))|(VAL<<BITSTARTPOS))
			
#define READBYTE(WORD,BITSTARTPOS)  ((WORD>>BITSTARTPOS)&255)				

#define READWRITEBIT(DWORD,DBIT,SWORD,SBIT)  DWORD=((DWORD&~(1<<DBIT))|(((SWORD>>SBIT)&1)<<DBIT))